/******************************************************************************
* By accessing or copying this work, you agree to comply with the following   *
* terms:                                                                      *
*                                                                             *
* Copyright (c) 2019-present mesibo                                              *
* https://mesibo.com                                                          *
* All rights reserved.                                                        *
*                                                                             *
* Redistribution is not permitted. Use of this software is subject to the     *
* conditions specified at https://mesibo.com . When using the source code,    *
* maintain the copyright notice, conditions, disclaimer, and  links to mesibo * 
* website, documentation and the source code repository.                      *
*                                                                             *
* Do not use the name of mesibo or its contributors to endorse products from  *
* this software without prior written permission.                             *
*                                                                             *
* This software is provided "as is" without warranties. mesibo and its        *
* contributors are not liable for any damages arising from its use.           *
*                                                                             *
* Documentation: https://docs.mesibo.com/                                     *
*                                                                             *
* Source Code Repository: https://github.com/mesibo/                          *
*******************************************************************************/

package com.mesibo.messaging.AllUtils;

import java.util.HashMap;
import java.util.Map;


public class TextToEmoji {

    private static HashMap<String, String> mEmojiMap;

    public static HashMap getEmojimap() {

        if (null == mEmojiMap) {
            mEmojiMap = new HashMap<String, String>();
            mEmojiMap.put(":+1:", new String(Character.toChars(0x1F44D)));
            mEmojiMap.put(":-1:", new String(Character.toChars(0x1F44E)));
            mEmojiMap.put(":100:", new String(Character.toChars(0x1F4AF)));
            mEmojiMap.put(":1234:", new String(Character.toChars(0x1F522)));
            mEmojiMap.put(":8ball:", new String(Character.toChars(0x1F3B1)));
            mEmojiMap.put(":a:", new String(Character.toChars(0x1F170)));
            mEmojiMap.put(":ab:", new String(Character.toChars(0x1F18E)));
            mEmojiMap.put(":abc:", new String(Character.toChars(0x1F524)));
            mEmojiMap.put(":abcd:", new String(Character.toChars(0x1F521)));
            mEmojiMap.put(":accept:", new String(Character.toChars(0x1F251)));
            mEmojiMap.put(":aerial_tramway:", new String(Character.toChars(0x1F6A1)));
            mEmojiMap.put(":alien:", new String(Character.toChars(0x1F47D)));
            mEmojiMap.put(":ambulance:", new String(Character.toChars(0x1F691)));
            mEmojiMap.put(":angel:", new String(Character.toChars(0x1F47C)));
            mEmojiMap.put(":anger:", new String(Character.toChars(0x1F4A2)));
            mEmojiMap.put(":angry:", new String(Character.toChars(0x1F620)));
            mEmojiMap.put(":anguished:", new String(Character.toChars(0x1F627)));
            mEmojiMap.put(":ant:", new String(Character.toChars(0x1F41C)));
            mEmojiMap.put(":apple:", new String(Character.toChars(0x1F34E)));
            mEmojiMap.put(":arrow_down_small:", new String(Character.toChars(0x1F53D)));
            mEmojiMap.put(":arrow_up_small:", new String(Character.toChars(0x1F53C)));
            mEmojiMap.put(":arrows_clockwise:", new String(Character.toChars(0x1F503)));
            mEmojiMap.put(":arrows_counterclockwise:",
                    new String(Character.toChars(0x1F504)));
            mEmojiMap.put(":art:", new String(Character.toChars(0x1F3A8)));
            mEmojiMap.put(":articulated_lorry:", new String(Character.toChars(0x1F69B)));
            mEmojiMap.put(":astonished:", new String(Character.toChars(0x1F632)));
            mEmojiMap.put(":athletic_shoe:", new String(Character.toChars(0x1F45F)));
            mEmojiMap.put(":atm:", new String(Character.toChars(0x1F3E7)));
            mEmojiMap.put(":b:", new String(Character.toChars(0x1F171)));
            mEmojiMap.put(":baby:", new String(Character.toChars(0x1F476)));
            mEmojiMap.put(":baby_bottle:", new String(Character.toChars(0x1F37C)));
            mEmojiMap.put(":baby_chick:", new String(Character.toChars(0x1F424)));
            mEmojiMap.put(":baby_symbol:", new String(Character.toChars(0x1F6BC)));
            mEmojiMap.put(":back:", new String(Character.toChars(0x1F519)));
            mEmojiMap.put(":baggage_claim:", new String(Character.toChars(0x1F6C4)));
            mEmojiMap.put(":balloon:", new String(Character.toChars(0x1F388)));
            mEmojiMap.put(":bamboo:", new String(Character.toChars(0x1F38D)));
            mEmojiMap.put(":banana:", new String(Character.toChars(0x1F34C)));
            mEmojiMap.put(":bank:", new String(Character.toChars(0x1F3E6)));
            mEmojiMap.put(":bar_chart:", new String(Character.toChars(0x1F4CA)));
            mEmojiMap.put(":barber:", new String(Character.toChars(0x1F488)));
            mEmojiMap.put(":basketball:", new String(Character.toChars(0x1F3C0)));
            mEmojiMap.put(":bath:", new String(Character.toChars(0x1F6C0)));
            mEmojiMap.put(":bathtub:", new String(Character.toChars(0x1F6C1)));
            mEmojiMap.put(":battery:", new String(Character.toChars(0x1F50B)));
            mEmojiMap.put(":bear:", new String(Character.toChars(0x1F43B)));
            mEmojiMap.put(":bee:", new String(Character.toChars(0x1F41D)));
            mEmojiMap.put(":beer:", new String(Character.toChars(0x1F37A)));
            mEmojiMap.put(":beers:", new String(Character.toChars(0x1F37B)));
            mEmojiMap.put(":beetle:", new String(Character.toChars(0x1F41E)));
            mEmojiMap.put(":beginner:", new String(Character.toChars(0x1F530)));
            mEmojiMap.put(":bell:", new String(Character.toChars(0x1F514)));
            mEmojiMap.put(":bento:", new String(Character.toChars(0x1F371)));
            mEmojiMap.put(":bicyclist:", new String(Character.toChars(0x1F6B4)));
            mEmojiMap.put(":bike:", new String(Character.toChars(0x1F6B2)));
            mEmojiMap.put(":bikini:", new String(Character.toChars(0x1F459)));
            mEmojiMap.put(":bird:", new String(Character.toChars(0x1F426)));
            mEmojiMap.put(":birthday:", new String(Character.toChars(0x1F382)));
            mEmojiMap.put(":black_joker:", new String(Character.toChars(0x1F0CF)));
            mEmojiMap.put(":black_square_button:", new String(Character.toChars(0x1F532)));
            mEmojiMap.put(":blossom:", new String(Character.toChars(0x1F33C)));
            mEmojiMap.put(":blowfish:", new String(Character.toChars(0x1F421)));
            mEmojiMap.put(":blue_book:", new String(Character.toChars(0x1F4D8)));
            mEmojiMap.put(":blue_car:", new String(Character.toChars(0x1F699)));
            mEmojiMap.put(":blue_heart:", new String(Character.toChars(0x1F499)));
            mEmojiMap.put(":blush:", new String(Character.toChars(0x1F60A)));
            mEmojiMap.put(":boar:", new String(Character.toChars(0x1F417)));
            mEmojiMap.put(":bomb:", new String(Character.toChars(0x1F4A3)));
            mEmojiMap.put(":book:", new String(Character.toChars(0x1F4D6)));
            mEmojiMap.put(":bookmark:", new String(Character.toChars(0x1F516)));
            mEmojiMap.put(":bookmark_tabs:", new String(Character.toChars(0x1F4D1)));
            mEmojiMap.put(":books:", new String(Character.toChars(0x1F4DA)));
            mEmojiMap.put(":boom:", new String(Character.toChars(0x1F4A5)));
            mEmojiMap.put(":boot:", new String(Character.toChars(0x1F462)));
            mEmojiMap.put(":bouquet:", new String(Character.toChars(0x1F490)));
            mEmojiMap.put(":bow:", new String(Character.toChars(0x1F647)));
            mEmojiMap.put(":bowling:", new String(Character.toChars(0x1F3B3)));
            mEmojiMap.put(":boy:", new String(Character.toChars(0x1F466)));
            mEmojiMap.put(":bread:", new String(Character.toChars(0x1F35E)));
            mEmojiMap.put(":bride_with_veil:", new String(Character.toChars(0x1F470)));
            mEmojiMap.put(":bridge_at_night:", new String(Character.toChars(0x1F309)));
            mEmojiMap.put(":briefcase:", new String(Character.toChars(0x1F4BC)));
            mEmojiMap.put(":broken_heart:", new String(Character.toChars(0x1F494)));
            mEmojiMap.put(":bug:", new String(Character.toChars(0x1F41B)));
            mEmojiMap.put(":bulb:", new String(Character.toChars(0x1F4A1)));
            mEmojiMap.put(":bullettrain_front:", new String(Character.toChars(0x1F685)));
            mEmojiMap.put(":bullettrain_side:", new String(Character.toChars(0x1F684)));
            mEmojiMap.put(":bus:", new String(Character.toChars(0x1F68C)));
            mEmojiMap.put(":busstop:", new String(Character.toChars(0x1F68F)));
            mEmojiMap.put(":bust_in_silhouette:", new String(Character.toChars(0x1F464)));
            mEmojiMap.put(":busts_in_silhouette:", new String(Character.toChars(0x1F465)));
            mEmojiMap.put(":cactus:", new String(Character.toChars(0x1F335)));
            mEmojiMap.put(":cake:", new String(Character.toChars(0x1F370)));
            mEmojiMap.put(":calendar:", new String(Character.toChars(0x1F4C6)));
            mEmojiMap.put(":calling:", new String(Character.toChars(0x1F4F2)));
            mEmojiMap.put(":camel:", new String(Character.toChars(0x1F42B)));
            mEmojiMap.put(":camera:", new String(Character.toChars(0x1F4F7)));
            mEmojiMap.put(":candy:", new String(Character.toChars(0x1F36C)));
            mEmojiMap.put(":capital_abcd:", new String(Character.toChars(0x1F520)));
            mEmojiMap.put(":car:", new String(Character.toChars(0x1F697)));
            mEmojiMap.put(":card_index:", new String(Character.toChars(0x1F4C7)));
            mEmojiMap.put(":carousel_horse:", new String(Character.toChars(0x1F3A0)));
            mEmojiMap.put(":cat:", new String(Character.toChars(0x1F431)));
            mEmojiMap.put(":cat2:", new String(Character.toChars(0x1F408)));
            mEmojiMap.put(":cd:", new String(Character.toChars(0x1F4BF)));
            mEmojiMap.put(":chart:", new String(Character.toChars(0x1F4B9)));
            mEmojiMap.put(":chart_with_downwards_trend:",
                    new String(Character.toChars(0x1F4C9)));
            mEmojiMap.put(":chart_with_upwards_trend:",
                    new String(Character.toChars(0x1F4C8)));
            mEmojiMap.put(":checkered_flag:", new String(Character.toChars(0x1F3C1)));
            mEmojiMap.put(":cherries:", new String(Character.toChars(0x1F352)));
            mEmojiMap.put(":cherry_blossom:", new String(Character.toChars(0x1F338)));
            mEmojiMap.put(":chestnut:", new String(Character.toChars(0x1F330)));
            mEmojiMap.put(":chicken:", new String(Character.toChars(0x1F414)));
            mEmojiMap.put(":children_crossing:", new String(Character.toChars(0x1F6B8)));
            mEmojiMap.put(":chocolate_bar:", new String(Character.toChars(0x1F36B)));
            mEmojiMap.put(":christmas_tree:", new String(Character.toChars(0x1F384)));
            mEmojiMap.put(":cinema:", new String(Character.toChars(0x1F3A6)));
            mEmojiMap.put(":circus_tent:", new String(Character.toChars(0x1F3AA)));
            mEmojiMap.put(":city_sunrise:", new String(Character.toChars(0x1F307)));
            mEmojiMap.put(":city_sunset:", new String(Character.toChars(0x1F306)));
            mEmojiMap.put(":cl:", new String(Character.toChars(0x1F191)));
            mEmojiMap.put(":clap:", new String(Character.toChars(0x1F44F)));
            mEmojiMap.put(":clapper:", new String(Character.toChars(0x1F3AC)));
            mEmojiMap.put(":clipboard:", new String(Character.toChars(0x1F4CB)));
            mEmojiMap.put(":clock1:", new String(Character.toChars(0x1F550)));
            mEmojiMap.put(":clock10:", new String(Character.toChars(0x1F559)));
            mEmojiMap.put(":clock1030:", new String(Character.toChars(0x1F565)));
            mEmojiMap.put(":clock11:", new String(Character.toChars(0x1F55A)));
            mEmojiMap.put(":clock1130:", new String(Character.toChars(0x1F566)));
            mEmojiMap.put(":clock12:", new String(Character.toChars(0x1F55B)));
            mEmojiMap.put(":clock1230:", new String(Character.toChars(0x1F567)));
            mEmojiMap.put(":clock130:", new String(Character.toChars(0x1F55C)));
            mEmojiMap.put(":clock2:", new String(Character.toChars(0x1F551)));
            mEmojiMap.put(":clock230:", new String(Character.toChars(0x1F55D)));
            mEmojiMap.put(":clock3:", new String(Character.toChars(0x1F552)));
            mEmojiMap.put(":clock330:", new String(Character.toChars(0x1F55E)));
            mEmojiMap.put(":clock4:", new String(Character.toChars(0x1F553)));
            mEmojiMap.put(":clock430:", new String(Character.toChars(0x1F55F)));
            mEmojiMap.put(":clock5:", new String(Character.toChars(0x1F554)));
            mEmojiMap.put(":clock530:", new String(Character.toChars(0x1F560)));
            mEmojiMap.put(":clock6:", new String(Character.toChars(0x1F555)));
            mEmojiMap.put(":clock630:", new String(Character.toChars(0x1F561)));
            mEmojiMap.put(":clock7:", new String(Character.toChars(0x1F556)));
            mEmojiMap.put(":clock730:", new String(Character.toChars(0x1F562)));
            mEmojiMap.put(":clock8:", new String(Character.toChars(0x1F557)));
            mEmojiMap.put(":clock830:", new String(Character.toChars(0x1F563)));
            mEmojiMap.put(":clock9:", new String(Character.toChars(0x1F558)));
            mEmojiMap.put(":clock930:", new String(Character.toChars(0x1F564)));
            mEmojiMap.put(":closed_book:", new String(Character.toChars(0x1F4D5)));
            mEmojiMap.put(":closed_lock_with_key:", new String(Character.toChars(0x1F510)));
            mEmojiMap.put(":closed_umbrella:", new String(Character.toChars(0x1F302)));
            mEmojiMap.put(":cocktail:", new String(Character.toChars(0x1F378)));
            mEmojiMap.put(":cold_sweat:", new String(Character.toChars(0x1F630)));
            mEmojiMap.put(":collision:", new String(Character.toChars(0x1F4A5)));
            mEmojiMap.put(":computer:", new String(Character.toChars(0x1F4BB)));
            mEmojiMap.put(":confetti_ball:", new String(Character.toChars(0x1F38A)));
            mEmojiMap.put(":confounded:", new String(Character.toChars(0x1F616)));
            mEmojiMap.put(":confused:", new String(Character.toChars(0x1F615)));
            mEmojiMap.put(":construction:", new String(Character.toChars(0x1F6A7)));
            mEmojiMap.put(":construction_worker:", new String(Character.toChars(0x1F477)));
            mEmojiMap.put(":convenience_store:", new String(Character.toChars(0x1F3EA)));
            mEmojiMap.put(":cookie:", new String(Character.toChars(0x1F36A)));
            mEmojiMap.put(":cool:", new String(Character.toChars(0x1F192)));
            mEmojiMap.put(":cop:", new String(Character.toChars(0x1F46E)));
            mEmojiMap.put(":corn:", new String(Character.toChars(0x1F33D)));
            mEmojiMap.put(":couple:", new String(Character.toChars(0x1F46B)));
            mEmojiMap.put(":couple_with_heart:", new String(Character.toChars(0x1F491)));
            mEmojiMap.put(":couplekiss:", new String(Character.toChars(0x1F48F)));
            mEmojiMap.put(":cow:", new String(Character.toChars(0x1F42E)));
            mEmojiMap.put(":cow2:", new String(Character.toChars(0x1F404)));
            mEmojiMap.put(":credit_card:", new String(Character.toChars(0x1F4B3)));
            mEmojiMap.put(":crocodile:", new String(Character.toChars(0x1F40A)));
            mEmojiMap.put(":crossed_flags:", new String(Character.toChars(0x1F38C)));
            mEmojiMap.put(":crown:", new String(Character.toChars(0x1F451)));
            mEmojiMap.put(":cry:", new String(Character.toChars(0x1F622)));
            mEmojiMap.put(":crying_cat_face:", new String(Character.toChars(0x1F63F)));
            mEmojiMap.put(":crystal_ball:", new String(Character.toChars(0x1F52E)));
            mEmojiMap.put(":cupid:", new String(Character.toChars(0x1F498)));
            mEmojiMap.put(":currency_exchange:", new String(Character.toChars(0x1F4B1)));
            mEmojiMap.put(":curry:", new String(Character.toChars(0x1F35B)));
            mEmojiMap.put(":custard:", new String(Character.toChars(0x1F36E)));
            mEmojiMap.put(":customs:", new String(Character.toChars(0x1F6C3)));
            mEmojiMap.put(":cyclone:", new String(Character.toChars(0x1F300)));
            mEmojiMap.put(":dancer:", new String(Character.toChars(0x1F483)));
            mEmojiMap.put(":dancers:", new String(Character.toChars(0x1F46F)));
            mEmojiMap.put(":dango:", new String(Character.toChars(0x1F361)));
            mEmojiMap.put(":dart:", new String(Character.toChars(0x1F3AF)));
            mEmojiMap.put(":dash:", new String(Character.toChars(0x1F4A8)));
            mEmojiMap.put(":date:", new String(Character.toChars(0x1F4C5)));
            mEmojiMap.put(":deciduous_tree:", new String(Character.toChars(0x1F333)));
            mEmojiMap.put(":department_store:", new String(Character.toChars(0x1F3EC)));
            mEmojiMap.put(":diamond_shape_with_a_dot_inside:",
                    new String(Character.toChars(0x1F4A0)));
            mEmojiMap.put(":disappointed:", new String(Character.toChars(0x1F61E)));
            mEmojiMap.put(":disappointed_relieved:", new String(Character.toChars(0x1F625)));
            mEmojiMap.put(":dizzy:", new String(Character.toChars(0x1F4AB)));
            mEmojiMap.put(":dizzy_face:", new String(Character.toChars(0x1F635)));
            mEmojiMap.put(":do_not_litter:", new String(Character.toChars(0x1F6AF)));
            mEmojiMap.put(":dog:", new String(Character.toChars(0x1F436)));
            mEmojiMap.put(":dog2:", new String(Character.toChars(0x1F415)));
            mEmojiMap.put(":dollar:", new String(Character.toChars(0x1F4B5)));
            mEmojiMap.put(":dolls:", new String(Character.toChars(0x1F38E)));
            mEmojiMap.put(":dolphin:", new String(Character.toChars(0x1F42C)));
            mEmojiMap.put(":door:", new String(Character.toChars(0x1F6AA)));
            mEmojiMap.put(":doughnut:", new String(Character.toChars(0x1F369)));
            mEmojiMap.put(":dragon:", new String(Character.toChars(0x1F409)));
            mEmojiMap.put(":dragon_face:", new String(Character.toChars(0x1F432)));
            mEmojiMap.put(":dress:", new String(Character.toChars(0x1F457)));
            mEmojiMap.put(":dromedary_camel:", new String(Character.toChars(0x1F42A)));
            mEmojiMap.put(":droplet:", new String(Character.toChars(0x1F4A7)));
            mEmojiMap.put(":dvd:", new String(Character.toChars(0x1F4C0)));
            mEmojiMap.put(":e-mail:", new String(Character.toChars(0x1F4E7)));
            mEmojiMap.put(":ear:", new String(Character.toChars(0x1F442)));
            mEmojiMap.put(":ear_of_rice:", new String(Character.toChars(0x1F33E)));
            mEmojiMap.put(":earth_africa:", new String(Character.toChars(0x1F30D)));
            mEmojiMap.put(":earth_americas:", new String(Character.toChars(0x1F30E)));
            mEmojiMap.put(":earth_asia:", new String(Character.toChars(0x1F30F)));
            mEmojiMap.put(":egg:", new String(Character.toChars(0x1F373)));
            mEmojiMap.put(":eggplant:", new String(Character.toChars(0x1F346)));
            mEmojiMap.put(":electric_plug:", new String(Character.toChars(0x1F50C)));
            mEmojiMap.put(":elephant:", new String(Character.toChars(0x1F418)));
            mEmojiMap.put(":end:", new String(Character.toChars(0x1F51A)));
            mEmojiMap.put(":envelope_with_arrow:", new String(Character.toChars(0x1F4E9)));
            mEmojiMap.put(":euro:", new String(Character.toChars(0x1F4B6)));
            mEmojiMap.put(":european_castle:", new String(Character.toChars(0x1F3F0)));
            mEmojiMap.put(":european_post_office:", new String(Character.toChars(0x1F3E4)));
            mEmojiMap.put(":evergreen_tree:", new String(Character.toChars(0x1F332)));
            mEmojiMap.put(":expressionless:", new String(Character.toChars(0x1F611)));
            mEmojiMap.put(":eyeglasses:", new String(Character.toChars(0x1F453)));
            mEmojiMap.put(":eyes:", new String(Character.toChars(0x1F440)));
            mEmojiMap.put(":facepunch:", new String(Character.toChars(0x1F44A)));
            mEmojiMap.put(":factory:", new String(Character.toChars(0x1F3ED)));
            mEmojiMap.put(":fallen_leaf:", new String(Character.toChars(0x1F342)));
            mEmojiMap.put(":family:", new String(Character.toChars(0x1F46A)));
            mEmojiMap.put(":fax:", new String(Character.toChars(0x1F4E0)));
            mEmojiMap.put(":fearful:", new String(Character.toChars(0x1F628)));
            mEmojiMap.put(":feet:", new String(Character.toChars(0x1F43E)));
            mEmojiMap.put(":ferris_wheel:", new String(Character.toChars(0x1F3A1)));
            mEmojiMap.put(":file_folder:", new String(Character.toChars(0x1F4C1)));
            mEmojiMap.put(":fire:", new String(Character.toChars(0x1F525)));
            mEmojiMap.put(":fire_engine:", new String(Character.toChars(0x1F692)));
            mEmojiMap.put(":fireworks:", new String(Character.toChars(0x1F386)));
            mEmojiMap.put(":first_quarter_moon:", new String(Character.toChars(0x1F313)));
            mEmojiMap.put(":first_quarter_moon_with_face:",
                    new String(Character.toChars(0x1F31B)));
            mEmojiMap.put(":fish:", new String(Character.toChars(0x1F41F)));
            mEmojiMap.put(":fish_cake:", new String(Character.toChars(0x1F365)));
            mEmojiMap.put(":fishing_pole_and_fish:", new String(Character.toChars(0x1F3A3)));
            mEmojiMap.put(":flags:", new String(Character.toChars(0x1F38F)));
            mEmojiMap.put(":flashlight:", new String(Character.toChars(0x1F526)));
            mEmojiMap.put(":floppy_disk:", new String(Character.toChars(0x1F4BE)));
            mEmojiMap.put(":flower_playing_cards:", new String(Character.toChars(0x1F3B4)));
            mEmojiMap.put(":flushed:", new String(Character.toChars(0x1F633)));
            mEmojiMap.put(":foggy:", new String(Character.toChars(0x1F301)));
            mEmojiMap.put(":football:", new String(Character.toChars(0x1F3C8)));
            mEmojiMap.put(":footprints:", new String(Character.toChars(0x1F463)));
            mEmojiMap.put(":fork_and_knife:", new String(Character.toChars(0x1F374)));
            mEmojiMap.put(":four_leaf_clover:", new String(Character.toChars(0x1F340)));
            mEmojiMap.put(":free:", new String(Character.toChars(0x1F193)));
            mEmojiMap.put(":fried_shrimp:", new String(Character.toChars(0x1F364)));
            mEmojiMap.put(":fries:", new String(Character.toChars(0x1F35F)));
            mEmojiMap.put(":frog:", new String(Character.toChars(0x1F438)));
            mEmojiMap.put(":frowning:", new String(Character.toChars(0x1F626)));
            mEmojiMap.put(":full_moon:", new String(Character.toChars(0x1F315)));
            mEmojiMap.put(":full_moon_with_face:", new String(Character.toChars(0x1F31D)));
            mEmojiMap.put(":game_die:", new String(Character.toChars(0x1F3B2)));
            mEmojiMap.put(":gem:", new String(Character.toChars(0x1F48E)));
            mEmojiMap.put(":ghost:", new String(Character.toChars(0x1F47B)));
            mEmojiMap.put(":gift:", new String(Character.toChars(0x1F381)));
            mEmojiMap.put(":gift_heart:", new String(Character.toChars(0x1F49D)));
            mEmojiMap.put(":girl:", new String(Character.toChars(0x1F467)));
            mEmojiMap.put(":globe_with_meridians:", new String(Character.toChars(0x1F310)));
            mEmojiMap.put(":goat:", new String(Character.toChars(0x1F410)));
            mEmojiMap.put(":grapes:", new String(Character.toChars(0x1F347)));
            mEmojiMap.put(":green_apple:", new String(Character.toChars(0x1F34F)));
            mEmojiMap.put(":green_book:", new String(Character.toChars(0x1F4D7)));
            mEmojiMap.put(":green_heart:", new String(Character.toChars(0x1F49A)));
            mEmojiMap.put(":grimacing:", new String(Character.toChars(0x1F62C)));
            mEmojiMap.put(":grin:", new String(Character.toChars(0x1F601)));
            mEmojiMap.put(":grinning:", new String(Character.toChars(0x1F600)));
            mEmojiMap.put(":guardsman:", new String(Character.toChars(0x1F482)));
            mEmojiMap.put(":guitar:", new String(Character.toChars(0x1F3B8)));
            mEmojiMap.put(":gun:", new String(Character.toChars(0x1F52B)));
            mEmojiMap.put(":haircut:", new String(Character.toChars(0x1F487)));
            mEmojiMap.put(":hamburger:", new String(Character.toChars(0x1F354)));
            mEmojiMap.put(":hammer:", new String(Character.toChars(0x1F528)));
            mEmojiMap.put(":hamster:", new String(Character.toChars(0x1F439)));
            mEmojiMap.put(":handbag:", new String(Character.toChars(0x1F45C)));
            mEmojiMap.put(":hankey:", new String(Character.toChars(0x1F4A9)));
            mEmojiMap.put(":hatched_chick:", new String(Character.toChars(0x1F425)));
            mEmojiMap.put(":hatching_chick:", new String(Character.toChars(0x1F423)));
            mEmojiMap.put(":headphones:", new String(Character.toChars(0x1F3A7)));
            mEmojiMap.put(":hear_no_evil:", new String(Character.toChars(0x1F649)));
            mEmojiMap.put(":heart_decoration:", new String(Character.toChars(0x1F49F)));
            mEmojiMap.put(":heart_eyes:", new String(Character.toChars(0x1F60D)));
            mEmojiMap.put(":heart_eyes_cat:", new String(Character.toChars(0x1F63B)));
            mEmojiMap.put(":heartbeat:", new String(Character.toChars(0x1F493)));
            mEmojiMap.put(":heartpulse:", new String(Character.toChars(0x1F497)));
            mEmojiMap.put(":heavy_dollar_sign:", new String(Character.toChars(0x1F4B2)));
            mEmojiMap.put(":helicopter:", new String(Character.toChars(0x1F681)));
            mEmojiMap.put(":herb:", new String(Character.toChars(0x1F33F)));
            mEmojiMap.put(":hibiscus:", new String(Character.toChars(0x1F33A)));
            mEmojiMap.put(":high_brightness:", new String(Character.toChars(0x1F506)));
            mEmojiMap.put(":high_heel:", new String(Character.toChars(0x1F460)));
            mEmojiMap.put(":hocho:", new String(Character.toChars(0x1F52A)));
            mEmojiMap.put(":honey_pot:", new String(Character.toChars(0x1F36F)));
            mEmojiMap.put(":honeybee:", new String(Character.toChars(0x1F41D)));
            mEmojiMap.put(":horse:", new String(Character.toChars(0x1F434)));
            mEmojiMap.put(":horse_racing:", new String(Character.toChars(0x1F3C7)));
            mEmojiMap.put(":hospital:", new String(Character.toChars(0x1F3E5)));
            mEmojiMap.put(":hotel:", new String(Character.toChars(0x1F3E8)));
            mEmojiMap.put(":house:", new String(Character.toChars(0x1F3E0)));
            mEmojiMap.put(":house_with_garden:", new String(Character.toChars(0x1F3E1)));
            mEmojiMap.put(":hushed:", new String(Character.toChars(0x1F62F)));
            mEmojiMap.put(":ice_cream:", new String(Character.toChars(0x1F368)));
            mEmojiMap.put(":icecream:", new String(Character.toChars(0x1F366)));
            mEmojiMap.put(":id:", new String(Character.toChars(0x1F194)));
            mEmojiMap.put(":ideograph_advantage:", new String(Character.toChars(0x1F250)));
            mEmojiMap.put(":imp:", new String(Character.toChars(0x1F47F)));
            mEmojiMap.put(":inbox_tray:", new String(Character.toChars(0x1F4E5)));
            mEmojiMap.put(":incoming_envelope:", new String(Character.toChars(0x1F4E8)));
            mEmojiMap.put(":information_desk_person:",
                    new String(Character.toChars(0x1F481)));
            mEmojiMap.put(":innocent:", new String(Character.toChars(0x1F607)));
            mEmojiMap.put(":iphone:", new String(Character.toChars(0x1F4F1)));
            mEmojiMap.put(":izakaya_lantern:", new String(Character.toChars(0x1F3EE)));
            mEmojiMap.put(":jack_o_lantern:", new String(Character.toChars(0x1F383)));
            mEmojiMap.put(":japan:", new String(Character.toChars(0x1F5FE)));
            mEmojiMap.put(":japanese_castle:", new String(Character.toChars(0x1F3EF)));
            mEmojiMap.put(":japanese_goblin:", new String(Character.toChars(0x1F47A)));
            mEmojiMap.put(":japanese_ogre:", new String(Character.toChars(0x1F479)));
            mEmojiMap.put(":jeans:", new String(Character.toChars(0x1F456)));
            mEmojiMap.put(":joy:", new String(Character.toChars(0x1F602)));
            mEmojiMap.put(":joy_cat:", new String(Character.toChars(0x1F639)));
            mEmojiMap.put(":key:", new String(Character.toChars(0x1F511)));
            mEmojiMap.put(":keycap_ten:", new String(Character.toChars(0x1F51F)));
            mEmojiMap.put(":kimono:", new String(Character.toChars(0x1F458)));
            mEmojiMap.put(":kiss:", new String(Character.toChars(0x1F48B)));
            mEmojiMap.put(":kissing:", new String(Character.toChars(0x1F617)));
            mEmojiMap.put(":kissing_cat:", new String(Character.toChars(0x1F63D)));
            mEmojiMap.put(":kissing_closed_eyes:", new String(Character.toChars(0x1F61A)));
            mEmojiMap.put(":kissing_heart:", new String(Character.toChars(0x1F618)));
            mEmojiMap.put(":kissing_smiling_eyes:", new String(Character.toChars(0x1F619)));
            mEmojiMap.put(":koala:", new String(Character.toChars(0x1F428)));
            mEmojiMap.put(":koko:", new String(Character.toChars(0x1F201)));
            mEmojiMap.put(":large_blue_circle:", new String(Character.toChars(0x1F535)));
            mEmojiMap.put(":large_blue_diamond:", new String(Character.toChars(0x1F537)));
            mEmojiMap.put(":large_orange_diamond:", new String(Character.toChars(0x1F536)));
            mEmojiMap.put(":last_quarter_moon:", new String(Character.toChars(0x1F317)));
            mEmojiMap.put(":last_quarter_moon_with_face:",
                    new String(Character.toChars(0x1F31C)));
            mEmojiMap.put(":laughing:", new String(Character.toChars(0x1F606)));
            mEmojiMap.put(":leaves:", new String(Character.toChars(0x1F343)));
            mEmojiMap.put(":ledger:", new String(Character.toChars(0x1F4D2)));
            mEmojiMap.put(":left_luggage:", new String(Character.toChars(0x1F6C5)));
            mEmojiMap.put(":lemon:", new String(Character.toChars(0x1F34B)));
            mEmojiMap.put(":leopard:", new String(Character.toChars(0x1F406)));
            mEmojiMap.put(":light_rail:", new String(Character.toChars(0x1F688)));
            mEmojiMap.put(":link:", new String(Character.toChars(0x1F517)));
            mEmojiMap.put(":lips:", new String(Character.toChars(0x1F444)));
            mEmojiMap.put(":lipstick:", new String(Character.toChars(0x1F484)));
            mEmojiMap.put(":lock:", new String(Character.toChars(0x1F512)));
            mEmojiMap.put(":lock_with_ink_pen:", new String(Character.toChars(0x1F50F)));
            mEmojiMap.put(":lollipop:", new String(Character.toChars(0x1F36D)));
            mEmojiMap.put(":loudspeaker:", new String(Character.toChars(0x1F4E2)));
            mEmojiMap.put(":love_hotel:", new String(Character.toChars(0x1F3E9)));
            mEmojiMap.put(":love_letter:", new String(Character.toChars(0x1F48C)));
            mEmojiMap.put(":low_brightness:", new String(Character.toChars(0x1F505)));
            mEmojiMap.put(":mag:", new String(Character.toChars(0x1F50D)));
            mEmojiMap.put(":mag_right:", new String(Character.toChars(0x1F50E)));
            mEmojiMap.put(":mahjong:", new String(Character.toChars(0x1F004)));
            mEmojiMap.put(":mailbox:", new String(Character.toChars(0x1F4EB)));
            mEmojiMap.put(":mailbox_closed:", new String(Character.toChars(0x1F4EA)));
            mEmojiMap.put(":mailbox_with_mail:", new String(Character.toChars(0x1F4EC)));
            mEmojiMap.put(":mailbox_with_no_mail:", new String(Character.toChars(0x1F4ED)));
            mEmojiMap.put(":man:", new String(Character.toChars(0x1F468)));
            mEmojiMap.put(":man_with_gua_pi_mao:", new String(Character.toChars(0x1F472)));
            mEmojiMap.put(":man_with_turban:", new String(Character.toChars(0x1F473)));
            mEmojiMap.put(":mans_shoe:", new String(Character.toChars(0x1F45E)));
            mEmojiMap.put(":maple_leaf:", new String(Character.toChars(0x1F341)));
            mEmojiMap.put(":mask:", new String(Character.toChars(0x1F637)));
            mEmojiMap.put(":massage:", new String(Character.toChars(0x1F486)));
            mEmojiMap.put(":meat_on_bone:", new String(Character.toChars(0x1F356)));
            mEmojiMap.put(":mega:", new String(Character.toChars(0x1F4E3)));
            mEmojiMap.put(":melon:", new String(Character.toChars(0x1F348)));
            mEmojiMap.put(":memo:", new String(Character.toChars(0x1F4DD)));
            mEmojiMap.put(":mens:", new String(Character.toChars(0x1F6B9)));
            mEmojiMap.put(":metro:", new String(Character.toChars(0x1F687)));
            mEmojiMap.put(":microphone:", new String(Character.toChars(0x1F3A4)));
            mEmojiMap.put(":microscope:", new String(Character.toChars(0x1F52C)));
            mEmojiMap.put(":milky_way:", new String(Character.toChars(0x1F30C)));
            mEmojiMap.put(":minibus:", new String(Character.toChars(0x1F690)));
            mEmojiMap.put(":minidisc:", new String(Character.toChars(0x1F4BD)));
            mEmojiMap.put(":mobile_phone_off:", new String(Character.toChars(0x1F4F4)));
            mEmojiMap.put(":money_with_wings:", new String(Character.toChars(0x1F4B8)));
            mEmojiMap.put(":moneybag:", new String(Character.toChars(0x1F4B0)));
            mEmojiMap.put(":monkey:", new String(Character.toChars(0x1F412)));
            mEmojiMap.put(":monkey_face:", new String(Character.toChars(0x1F435)));
            mEmojiMap.put(":monorail:", new String(Character.toChars(0x1F69D)));
            mEmojiMap.put(":moon:", new String(Character.toChars(0x1F319)));
            mEmojiMap.put(":mortar_board:", new String(Character.toChars(0x1F393)));
            mEmojiMap.put(":mount_fuji:", new String(Character.toChars(0x1F5FB)));
            mEmojiMap.put(":mountain_bicyclist:", new String(Character.toChars(0x1F6B5)));
            mEmojiMap.put(":mountain_cableway:", new String(Character.toChars(0x1F6A0)));
            mEmojiMap.put(":mountain_railway:", new String(Character.toChars(0x1F69E)));
            mEmojiMap.put(":mouse:", new String(Character.toChars(0x1F42D)));
            mEmojiMap.put(":mouse2:", new String(Character.toChars(0x1F401)));
            mEmojiMap.put(":movie_camera:", new String(Character.toChars(0x1F3A5)));
            mEmojiMap.put(":moyai:", new String(Character.toChars(0x1F5FF)));
            mEmojiMap.put(":muscle:", new String(Character.toChars(0x1F4AA)));
            mEmojiMap.put(":mushroom:", new String(Character.toChars(0x1F344)));
            mEmojiMap.put(":musical_keyboard:", new String(Character.toChars(0x1F3B9)));
            mEmojiMap.put(":musical_note:", new String(Character.toChars(0x1F3B5)));
            mEmojiMap.put(":musical_score:", new String(Character.toChars(0x1F3BC)));
            mEmojiMap.put(":mute:", new String(Character.toChars(0x1F507)));
            mEmojiMap.put(":nail_care:", new String(Character.toChars(0x1F485)));
            mEmojiMap.put(":name_badge:", new String(Character.toChars(0x1F4DB)));
            mEmojiMap.put(":necktie:", new String(Character.toChars(0x1F454)));
            mEmojiMap.put(":neutral_face:", new String(Character.toChars(0x1F610)));
            mEmojiMap.put(":new:", new String(Character.toChars(0x1F195)));
            mEmojiMap.put(":new_moon:", new String(Character.toChars(0x1F311)));
            mEmojiMap.put(":new_moon_with_face:", new String(Character.toChars(0x1F31A)));
            mEmojiMap.put(":newspaper:", new String(Character.toChars(0x1F4F0)));
            mEmojiMap.put(":ng:", new String(Character.toChars(0x1F196)));
            mEmojiMap.put(":no_bell:", new String(Character.toChars(0x1F515)));
            mEmojiMap.put(":no_bicycles:", new String(Character.toChars(0x1F6B3)));
            mEmojiMap.put(":no_entry_sign:", new String(Character.toChars(0x1F6AB)));
            mEmojiMap.put(":no_good:", new String(Character.toChars(0x1F645)));
            mEmojiMap.put(":no_mobile_phones:", new String(Character.toChars(0x1F4F5)));
            mEmojiMap.put(":no_mouth:", new String(Character.toChars(0x1F636)));
            mEmojiMap.put(":no_pedestrians:", new String(Character.toChars(0x1F6B7)));
            mEmojiMap.put(":no_smoking:", new String(Character.toChars(0x1F6AD)));
            mEmojiMap.put(":non-potable_water:", new String(Character.toChars(0x1F6B1)));
            mEmojiMap.put(":nose:", new String(Character.toChars(0x1F443)));
            mEmojiMap.put(":notebook:", new String(Character.toChars(0x1F4D3)));
            mEmojiMap.put(":notebook_with_decorative_cover:",
                    new String(Character.toChars(0x1F4D4)));
            mEmojiMap.put(":notes:", new String(Character.toChars(0x1F3B6)));
            mEmojiMap.put(":nut_and_bolt:", new String(Character.toChars(0x1F529)));
            mEmojiMap.put(":o2:", new String(Character.toChars(0x1F17E)));
            mEmojiMap.put(":ocean:", new String(Character.toChars(0x1F30A)));
            mEmojiMap.put(":octopus:", new String(Character.toChars(0x1F419)));
            mEmojiMap.put(":oden:", new String(Character.toChars(0x1F362)));
            mEmojiMap.put(":office:", new String(Character.toChars(0x1F3E2)));
            mEmojiMap.put(":ok:", new String(Character.toChars(0x1F197)));
            mEmojiMap.put(":ok_hand:", new String(Character.toChars(0x1F44C)));
            mEmojiMap.put(":ok_woman:", new String(Character.toChars(0x1F646)));
            mEmojiMap.put(":older_man:", new String(Character.toChars(0x1F474)));
            mEmojiMap.put(":older_woman:", new String(Character.toChars(0x1F475)));
            mEmojiMap.put(":on:", new String(Character.toChars(0x1F51B)));
            mEmojiMap.put(":oncoming_automobile:", new String(Character.toChars(0x1F698)));
            mEmojiMap.put(":oncoming_bus:", new String(Character.toChars(0x1F68D)));
            mEmojiMap.put(":oncoming_police_car:", new String(Character.toChars(0x1F694)));
            mEmojiMap.put(":oncoming_taxi:", new String(Character.toChars(0x1F696)));
            mEmojiMap.put(":open_book:", new String(Character.toChars(0x1F4D6)));
            mEmojiMap.put(":open_file_folder:", new String(Character.toChars(0x1F4C2)));
            mEmojiMap.put(":open_hands:", new String(Character.toChars(0x1F450)));
            mEmojiMap.put(":open_mouth:", new String(Character.toChars(0x1F62E)));
            mEmojiMap.put(":orange_book:", new String(Character.toChars(0x1F4D9)));
            mEmojiMap.put(":outbox_tray:", new String(Character.toChars(0x1F4E4)));
            mEmojiMap.put(":ox:", new String(Character.toChars(0x1F402)));
            mEmojiMap.put(":package:", new String(Character.toChars(0x1F4E6)));
            mEmojiMap.put(":page_facing_up:", new String(Character.toChars(0x1F4C4)));
            mEmojiMap.put(":page_with_curl:", new String(Character.toChars(0x1F4C3)));
            mEmojiMap.put(":pager:", new String(Character.toChars(0x1F4DF)));
            mEmojiMap.put(":palm_tree:", new String(Character.toChars(0x1F334)));
            mEmojiMap.put(":panda_face:", new String(Character.toChars(0x1F43C)));
            mEmojiMap.put(":paperclip:", new String(Character.toChars(0x1F4CE)));
            mEmojiMap.put(":parking:", new String(Character.toChars(0x1F17F)));
            mEmojiMap.put(":passport_control:", new String(Character.toChars(0x1F6C2)));
            mEmojiMap.put(":paw_prints:", new String(Character.toChars(0x1F43E)));
            mEmojiMap.put(":peach:", new String(Character.toChars(0x1F351)));
            mEmojiMap.put(":pear:", new String(Character.toChars(0x1F350)));
            mEmojiMap.put(":pencil:", new String(Character.toChars(0x1F4DD)));
            mEmojiMap.put(":penguin:", new String(Character.toChars(0x1F427)));
            mEmojiMap.put(":pensive:", new String(Character.toChars(0x1F614)));
            mEmojiMap.put(":performing_arts:", new String(Character.toChars(0x1F3AD)));
            mEmojiMap.put(":persevere:", new String(Character.toChars(0x1F623)));
            mEmojiMap.put(":person_frowning:", new String(Character.toChars(0x1F64D)));
            mEmojiMap.put(":person_with_blond_hair:",
                    new String(Character.toChars(0x1F471)));
            mEmojiMap.put(":person_with_pouting_face:",
                    new String(Character.toChars(0x1F64E)));
            mEmojiMap.put(":pig:", new String(Character.toChars(0x1F437)));
            mEmojiMap.put(":pig2:", new String(Character.toChars(0x1F416)));
            mEmojiMap.put(":pig_nose:", new String(Character.toChars(0x1F43D)));
            mEmojiMap.put(":pill:", new String(Character.toChars(0x1F48A)));
            mEmojiMap.put(":pineapple:", new String(Character.toChars(0x1F34D)));
            mEmojiMap.put(":pizza:", new String(Character.toChars(0x1F355)));
            mEmojiMap.put(":point_down:", new String(Character.toChars(0x1F447)));
            mEmojiMap.put(":point_left:", new String(Character.toChars(0x1F448)));
            mEmojiMap.put(":point_right:", new String(Character.toChars(0x1F449)));
            mEmojiMap.put(":point_up_2:", new String(Character.toChars(0x1F446)));
            mEmojiMap.put(":police_car:", new String(Character.toChars(0x1F693)));
            mEmojiMap.put(":poodle:", new String(Character.toChars(0x1F429)));
            mEmojiMap.put(":poop:", new String(Character.toChars(0x1F4A9)));
            mEmojiMap.put(":post_office:", new String(Character.toChars(0x1F3E3)));
            mEmojiMap.put(":postal_horn:", new String(Character.toChars(0x1F4EF)));
            mEmojiMap.put(":postbox:", new String(Character.toChars(0x1F4EE)));
            mEmojiMap.put(":potable_water:", new String(Character.toChars(0x1F6B0)));
            mEmojiMap.put(":pouch:", new String(Character.toChars(0x1F45D)));
            mEmojiMap.put(":poultry_leg:", new String(Character.toChars(0x1F357)));
            mEmojiMap.put(":pound:", new String(Character.toChars(0x1F4B7)));
            mEmojiMap.put(":pouting_cat:", new String(Character.toChars(0x1F63E)));
            mEmojiMap.put(":pray:", new String(Character.toChars(0x1F64F)));
            mEmojiMap.put(":princess:", new String(Character.toChars(0x1F478)));
            mEmojiMap.put(":punch:", new String(Character.toChars(0x1F44A)));
            mEmojiMap.put(":purple_heart:", new String(Character.toChars(0x1F49C)));
            mEmojiMap.put(":purse:", new String(Character.toChars(0x1F45B)));
            mEmojiMap.put(":pushpin:", new String(Character.toChars(0x1F4CC)));
            mEmojiMap.put(":put_litter_in_its_place:",
                    new String(Character.toChars(0x1F6AE)));
            mEmojiMap.put(":rabbit:", new String(Character.toChars(0x1F430)));
            mEmojiMap.put(":rabbit2:", new String(Character.toChars(0x1F407)));
            mEmojiMap.put(":racehorse:", new String(Character.toChars(0x1F40E)));
            mEmojiMap.put(":radio:", new String(Character.toChars(0x1F4FB)));
            mEmojiMap.put(":radio_button:", new String(Character.toChars(0x1F518)));
            mEmojiMap.put(":rage:", new String(Character.toChars(0x1F621)));
            mEmojiMap.put(":railway_car:", new String(Character.toChars(0x1F683)));
            mEmojiMap.put(":rainbow:", new String(Character.toChars(0x1F308)));
            mEmojiMap.put(":raised_hands:", new String(Character.toChars(0x1F64C)));
            mEmojiMap.put(":raising_hand:", new String(Character.toChars(0x1F64B)));
            mEmojiMap.put(":ram:", new String(Character.toChars(0x1F40F)));
            mEmojiMap.put(":ramen:", new String(Character.toChars(0x1F35C)));
            mEmojiMap.put(":rat:", new String(Character.toChars(0x1F400)));
            mEmojiMap.put(":red_car:", new String(Character.toChars(0x1F697)));
            mEmojiMap.put(":red_circle:", new String(Character.toChars(0x1F534)));
            mEmojiMap.put(":relieved:", new String(Character.toChars(0x1F60C)));
            mEmojiMap.put(":repeat:", new String(Character.toChars(0x1F501)));
            mEmojiMap.put(":repeat_one:", new String(Character.toChars(0x1F502)));
            mEmojiMap.put(":restroom:", new String(Character.toChars(0x1F6BB)));
            mEmojiMap.put(":revolving_hearts:", new String(Character.toChars(0x1F49E)));
            mEmojiMap.put(":ribbon:", new String(Character.toChars(0x1F380)));
            mEmojiMap.put(":rice:", new String(Character.toChars(0x1F35A)));
            mEmojiMap.put(":rice_ball:", new String(Character.toChars(0x1F359)));
            mEmojiMap.put(":rice_cracker:", new String(Character.toChars(0x1F358)));
            mEmojiMap.put(":rice_scene:", new String(Character.toChars(0x1F391)));
            mEmojiMap.put(":ring:", new String(Character.toChars(0x1F48D)));
            mEmojiMap.put(":rocket:", new String(Character.toChars(0x1F680)));
            mEmojiMap.put(":roller_coaster:", new String(Character.toChars(0x1F3A2)));
            mEmojiMap.put(":rooster:", new String(Character.toChars(0x1F413)));
            mEmojiMap.put(":rose:", new String(Character.toChars(0x1F339)));
            mEmojiMap.put(":rotating_light:", new String(Character.toChars(0x1F6A8)));
            mEmojiMap.put(":round_pushpin:", new String(Character.toChars(0x1F4CD)));
            mEmojiMap.put(":rowboat:", new String(Character.toChars(0x1F6A3)));
            mEmojiMap.put(":rugby_football:", new String(Character.toChars(0x1F3C9)));
            mEmojiMap.put(":runner:", new String(Character.toChars(0x1F3C3)));
            mEmojiMap.put(":running:", new String(Character.toChars(0x1F3C3)));
            mEmojiMap.put(":running_shirt_with_sash:",
                    new String(Character.toChars(0x1F3BD)));
            mEmojiMap.put(":sa:", new String(Character.toChars(0x1F202)));
            mEmojiMap.put(":sake:", new String(Character.toChars(0x1F376)));
            mEmojiMap.put(":sandal:", new String(Character.toChars(0x1F461)));
            mEmojiMap.put(":santa:", new String(Character.toChars(0x1F385)));
            mEmojiMap.put(":satellite:", new String(Character.toChars(0x1F4E1)));
            mEmojiMap.put(":satisfied:", new String(Character.toChars(0x1F606)));
            mEmojiMap.put(":saxophone:", new String(Character.toChars(0x1F3B7)));
            mEmojiMap.put(":school:", new String(Character.toChars(0x1F3EB)));
            mEmojiMap.put(":school_satchel:", new String(Character.toChars(0x1F392)));
            mEmojiMap.put(":scream:", new String(Character.toChars(0x1F631)));
            mEmojiMap.put(":scream_cat:", new String(Character.toChars(0x1F640)));
            mEmojiMap.put(":scroll:", new String(Character.toChars(0x1F4DC)));
            mEmojiMap.put(":seat:", new String(Character.toChars(0x1F4BA)));
            mEmojiMap.put(":see_no_evil:", new String(Character.toChars(0x1F648)));
            mEmojiMap.put(":seedling:", new String(Character.toChars(0x1F331)));
            mEmojiMap.put(":shaved_ice:", new String(Character.toChars(0x1F367)));
            mEmojiMap.put(":sheep:", new String(Character.toChars(0x1F411)));
            mEmojiMap.put(":shell:", new String(Character.toChars(0x1F41A)));
            mEmojiMap.put(":ship:", new String(Character.toChars(0x1F6A2)));
            mEmojiMap.put(":shirt:", new String(Character.toChars(0x1F455)));
            mEmojiMap.put(":shit:", new String(Character.toChars(0x1F4A9)));
            mEmojiMap.put(":shoe:", new String(Character.toChars(0x1F45E)));
            mEmojiMap.put(":shower:", new String(Character.toChars(0x1F6BF)));
            mEmojiMap.put(":signal_strength:", new String(Character.toChars(0x1F4F6)));
            mEmojiMap.put(":six_pointed_star:", new String(Character.toChars(0x1F52F)));
            mEmojiMap.put(":ski:", new String(Character.toChars(0x1F3BF)));
            mEmojiMap.put(":skull:", new String(Character.toChars(0x1F480)));
            mEmojiMap.put(":sleeping:", new String(Character.toChars(0x1F634)));
            mEmojiMap.put(":sleepy:", new String(Character.toChars(0x1F62A)));
            mEmojiMap.put(":slot_machine:", new String(Character.toChars(0x1F3B0)));
            mEmojiMap.put(":small_blue_diamond:", new String(Character.toChars(0x1F539)));
            mEmojiMap.put(":small_orange_diamond:", new String(Character.toChars(0x1F538)));
            mEmojiMap.put(":small_red_triangle:", new String(Character.toChars(0x1F53A)));
            mEmojiMap.put(":small_red_triangle_down:",
                    new String(Character.toChars(0x1F53B)));
            mEmojiMap.put(":smile:", new String(Character.toChars(0x1F604)));
            mEmojiMap.put(":smile_cat:", new String(Character.toChars(0x1F638)));
            mEmojiMap.put(":smiley:", new String(Character.toChars(0x1F603)));
            mEmojiMap.put(":smiley_cat:", new String(Character.toChars(0x1F63A)));
            mEmojiMap.put(":smiling_imp:", new String(Character.toChars(0x1F608)));
            mEmojiMap.put(":smirk:", new String(Character.toChars(0x1F60F)));
            mEmojiMap.put(":smirk_cat:", new String(Character.toChars(0x1F63C)));
            mEmojiMap.put(":smoking:", new String(Character.toChars(0x1F6AC)));
            mEmojiMap.put(":snail:", new String(Character.toChars(0x1F40C)));
            mEmojiMap.put(":snake:", new String(Character.toChars(0x1F40D)));
            mEmojiMap.put(":snowboarder:", new String(Character.toChars(0x1F3C2)));
            mEmojiMap.put(":sob:", new String(Character.toChars(0x1F62D)));
            mEmojiMap.put(":soon:", new String(Character.toChars(0x1F51C)));
            mEmojiMap.put(":sos:", new String(Character.toChars(0x1F198)));
            mEmojiMap.put(":sound:", new String(Character.toChars(0x1F509)));
            mEmojiMap.put(":space_invader:", new String(Character.toChars(0x1F47E)));
            mEmojiMap.put(":spaghetti:", new String(Character.toChars(0x1F35D)));
            mEmojiMap.put(":sparkler:", new String(Character.toChars(0x1F387)));
            mEmojiMap.put(":sparkling_heart:", new String(Character.toChars(0x1F496)));
            mEmojiMap.put(":speak_no_evil:", new String(Character.toChars(0x1F64A)));
            mEmojiMap.put(":speaker:", new String(Character.toChars(0x1F50A)));
            mEmojiMap.put(":speech_balloon:", new String(Character.toChars(0x1F4AC)));
            mEmojiMap.put(":speedboat:", new String(Character.toChars(0x1F6A4)));
            mEmojiMap.put(":star2:", new String(Character.toChars(0x1F31F)));
            mEmojiMap.put(":stars:", new String(Character.toChars(0x1F303)));
            mEmojiMap.put(":station:", new String(Character.toChars(0x1F689)));
            mEmojiMap.put(":statue_of_liberty:", new String(Character.toChars(0x1F5FD)));
            mEmojiMap.put(":steam_locomotive:", new String(Character.toChars(0x1F682)));
            mEmojiMap.put(":stew:", new String(Character.toChars(0x1F372)));
            mEmojiMap.put(":straight_ruler:", new String(Character.toChars(0x1F4CF)));
            mEmojiMap.put(":strawberry:", new String(Character.toChars(0x1F353)));
            mEmojiMap.put(":stuck_out_tongue:", new String(Character.toChars(0x1F61B)));
            mEmojiMap.put(":stuck_out_tongue_closed_eyes:",
                    new String(Character.toChars(0x1F61D)));
            mEmojiMap.put(":stuck_out_tongue_winking_eye:",
                    new String(Character.toChars(0x1F61C)));
            mEmojiMap.put(":sun_with_face:", new String(Character.toChars(0x1F31E)));
            mEmojiMap.put(":sunflower:", new String(Character.toChars(0x1F33B)));
            mEmojiMap.put(":sunglasses:", new String(Character.toChars(0x1F60E)));
            mEmojiMap.put(":sunrise:", new String(Character.toChars(0x1F305)));
            mEmojiMap.put(":sunrise_over_mountains:",
                    new String(Character.toChars(0x1F304)));
            mEmojiMap.put(":surfer:", new String(Character.toChars(0x1F3C4)));
            mEmojiMap.put(":sushi:", new String(Character.toChars(0x1F363)));
            mEmojiMap.put(":suspension_railway:", new String(Character.toChars(0x1F69F)));
            mEmojiMap.put(":sweat:", new String(Character.toChars(0x1F613)));
            mEmojiMap.put(":sweat_drops:", new String(Character.toChars(0x1F4A6)));
            mEmojiMap.put(":sweat_smile:", new String(Character.toChars(0x1F605)));
            mEmojiMap.put(":sweet_potato:", new String(Character.toChars(0x1F360)));
            mEmojiMap.put(":swimmer:", new String(Character.toChars(0x1F3CA)));
            mEmojiMap.put(":symbols:", new String(Character.toChars(0x1F523)));
            mEmojiMap.put(":syringe:", new String(Character.toChars(0x1F489)));
            mEmojiMap.put(":tada:", new String(Character.toChars(0x1F389)));
            mEmojiMap.put(":tanabata_tree:", new String(Character.toChars(0x1F38B)));
            mEmojiMap.put(":tangerine:", new String(Character.toChars(0x1F34A)));
            mEmojiMap.put(":taxi:", new String(Character.toChars(0x1F695)));
            mEmojiMap.put(":tea:", new String(Character.toChars(0x1F375)));
            mEmojiMap.put(":telephone_receiver:", new String(Character.toChars(0x1F4DE)));
            mEmojiMap.put(":telescope:", new String(Character.toChars(0x1F52D)));
            mEmojiMap.put(":tennis:", new String(Character.toChars(0x1F3BE)));
            mEmojiMap.put(":thought_balloon:", new String(Character.toChars(0x1F4AD)));
            mEmojiMap.put(":thumbsdown:", new String(Character.toChars(0x1F44E)));
            mEmojiMap.put(":thumbsup:", new String(Character.toChars(0x1F44D)));
            mEmojiMap.put(":ticket:", new String(Character.toChars(0x1F3AB)));
            mEmojiMap.put(":tiger:", new String(Character.toChars(0x1F42F)));
            mEmojiMap.put(":tiger2:", new String(Character.toChars(0x1F405)));
            mEmojiMap.put(":tired_face:", new String(Character.toChars(0x1F62B)));
            mEmojiMap.put(":toilet:", new String(Character.toChars(0x1F6BD)));
            mEmojiMap.put(":tokyo_tower:", new String(Character.toChars(0x1F5FC)));
            mEmojiMap.put(":tomato:", new String(Character.toChars(0x1F345)));
            mEmojiMap.put(":tongue:", new String(Character.toChars(0x1F445)));
            mEmojiMap.put(":top:", new String(Character.toChars(0x1F51D)));
            mEmojiMap.put(":tophat:", new String(Character.toChars(0x1F3A9)));
            mEmojiMap.put(":tractor:", new String(Character.toChars(0x1F69C)));
            mEmojiMap.put(":traffic_light:", new String(Character.toChars(0x1F6A5)));
            mEmojiMap.put(":train:", new String(Character.toChars(0x1F683)));
            mEmojiMap.put(":train2:", new String(Character.toChars(0x1F686)));
            mEmojiMap.put(":tram:", new String(Character.toChars(0x1F68A)));
            mEmojiMap.put(":triangular_flag_on_post:",
                    new String(Character.toChars(0x1F6A9)));
            mEmojiMap.put(":triangular_ruler:", new String(Character.toChars(0x1F4D0)));
            mEmojiMap.put(":trident:", new String(Character.toChars(0x1F531)));
            mEmojiMap.put(":triumph:", new String(Character.toChars(0x1F624)));
            mEmojiMap.put(":trolleybus:", new String(Character.toChars(0x1F68E)));
            mEmojiMap.put(":trophy:", new String(Character.toChars(0x1F3C6)));
            mEmojiMap.put(":tropical_drink:", new String(Character.toChars(0x1F379)));
            mEmojiMap.put(":tropical_fish:", new String(Character.toChars(0x1F420)));
            mEmojiMap.put(":truck:", new String(Character.toChars(0x1F69A)));
            mEmojiMap.put(":trumpet:", new String(Character.toChars(0x1F3BA)));
            mEmojiMap.put(":tshirt:", new String(Character.toChars(0x1F455)));
            mEmojiMap.put(":tulip:", new String(Character.toChars(0x1F337)));
            mEmojiMap.put(":turtle:", new String(Character.toChars(0x1F422)));
            mEmojiMap.put(":tv:", new String(Character.toChars(0x1F4FA)));
            mEmojiMap.put(":twisted_rightwards_arrows:",
                    new String(Character.toChars(0x1F500)));
            mEmojiMap.put(":two_hearts:", new String(Character.toChars(0x1F495)));
            mEmojiMap.put(":two_men_holding_hands:", new String(Character.toChars(0x1F46C)));
            mEmojiMap.put(":two_women_holding_hands:",
                    new String(Character.toChars(0x1F46D)));
            mEmojiMap.put(":u5272:", new String(Character.toChars(0x1F239)));
            mEmojiMap.put(":u5408:", new String(Character.toChars(0x1F234)));
            mEmojiMap.put(":u55b6:", new String(Character.toChars(0x1F23A)));
            mEmojiMap.put(":u6307:", new String(Character.toChars(0x1F22F)));
            mEmojiMap.put(":u6708:", new String(Character.toChars(0x1F237)));
            mEmojiMap.put(":u6709:", new String(Character.toChars(0x1F236)));
            mEmojiMap.put(":u6e80:", new String(Character.toChars(0x1F235)));
            mEmojiMap.put(":u7121:", new String(Character.toChars(0x1F21A)));
            mEmojiMap.put(":u7533:", new String(Character.toChars(0x1F238)));
            mEmojiMap.put(":u7981:", new String(Character.toChars(0x1F232)));
            mEmojiMap.put(":u7a7a:", new String(Character.toChars(0x1F233)));
            mEmojiMap.put(":unamused:", new String(Character.toChars(0x1F612)));
            mEmojiMap.put(":underage:", new String(Character.toChars(0x1F51E)));
            mEmojiMap.put(":unlock:", new String(Character.toChars(0x1F513)));
            mEmojiMap.put(":up:", new String(Character.toChars(0x1F199)));
            mEmojiMap.put(":vertical_traffic_light:",
                    new String(Character.toChars(0x1F6A6)));
            mEmojiMap.put(":vhs:", new String(Character.toChars(0x1F4FC)));
            mEmojiMap.put(":vibration_mode:", new String(Character.toChars(0x1F4F3)));
            mEmojiMap.put(":video_camera:", new String(Character.toChars(0x1F4F9)));
            mEmojiMap.put(":video_game:", new String(Character.toChars(0x1F3AE)));
            mEmojiMap.put(":violin:", new String(Character.toChars(0x1F3BB)));
            mEmojiMap.put(":volcano:", new String(Character.toChars(0x1F30B)));
            mEmojiMap.put(":vs:", new String(Character.toChars(0x1F19A)));
            mEmojiMap.put(":walking:", new String(Character.toChars(0x1F6B6)));
            mEmojiMap.put(":waning_crescent_moon:", new String(Character.toChars(0x1F318)));
            mEmojiMap.put(":waning_gibbous_moon:", new String(Character.toChars(0x1F316)));
            mEmojiMap.put(":water_buffalo:", new String(Character.toChars(0x1F403)));
            mEmojiMap.put(":watermelon:", new String(Character.toChars(0x1F349)));
            mEmojiMap.put(":wave:", new String(Character.toChars(0x1F44B)));
            mEmojiMap.put(":waxing_crescent_moon:", new String(Character.toChars(0x1F312)));
            mEmojiMap.put(":waxing_gibbous_moon:", new String(Character.toChars(0x1F314)));
            mEmojiMap.put(":wc:", new String(Character.toChars(0x1F6BE)));
            mEmojiMap.put(":weary:", new String(Character.toChars(0x1F629)));
            mEmojiMap.put(":wedding:", new String(Character.toChars(0x1F492)));
            mEmojiMap.put(":whale:", new String(Character.toChars(0x1F433)));
            mEmojiMap.put(":whale2:", new String(Character.toChars(0x1F40B)));
            mEmojiMap.put(":white_flower:", new String(Character.toChars(0x1F4AE)));
            mEmojiMap.put(":white_square_button:", new String(Character.toChars(0x1F533)));
            mEmojiMap.put(":wind_chime:", new String(Character.toChars(0x1F390)));
            mEmojiMap.put(":wine_glass:", new String(Character.toChars(0x1F377)));
            mEmojiMap.put(":wink:", new String(Character.toChars(0x1F609)));
            mEmojiMap.put(":wolf:", new String(Character.toChars(0x1F43A)));
            mEmojiMap.put(":woman:", new String(Character.toChars(0x1F469)));
            mEmojiMap.put(":womans_clothes:", new String(Character.toChars(0x1F45A)));
            mEmojiMap.put(":womans_hat:", new String(Character.toChars(0x1F452)));
            mEmojiMap.put(":womens:", new String(Character.toChars(0x1F6BA)));
            mEmojiMap.put(":worried:", new String(Character.toChars(0x1F61F)));
            mEmojiMap.put(":wrench:", new String(Character.toChars(0x1F527)));
            mEmojiMap.put(":yellow_heart:", new String(Character.toChars(0x1F49B)));
            mEmojiMap.put(":yen:", new String(Character.toChars(0x1F4B4)));
            mEmojiMap.put(":yum:", new String(Character.toChars(0x1F60B)));
            mEmojiMap.put(":zzz:", new String(Character.toChars(0x1F4A4)));
        }
        return mEmojiMap;

    }
}
